package culture

var mockBases = []string{
	"nordic_europe_base",
	"europe_continental_base",
	"caucasian_base",
	"mediterranean_base",
	"semitic_base",
	"egyptian_base",
	"berber_base",
	"mesopotamian_base",
	"persian_base",
	"turkic_base",
	"chinese_base",
	"mongolian_base",
	"indian_base",
	"african_base",
	"maya_base",
	"north_america_base",
	"inca_base",
	"inuit_base",
	"polynesian_base",
	"elven_base",
	"dark_elven_base",
	"dwarven_base",
	"goblin_base",
	"orc_base",
	"giant_base",
	"draconic_base",
	"arachnid_base",
	"serpents_base",
}
