package culture

var mockEthoses = []Ethos{
	{
		Slug:             "bellicose_ethos",
		IsDiplomatic:     false,
		IsWarlike:        true,
		IsAdministrative: false,
		IsIntrigue:       true,
		IsScholarly:      false,
	},
	{
		Slug:             "bureaucratic_ethos",
		IsDiplomatic:     false,
		IsWarlike:        true,
		IsAdministrative: true,
		IsIntrigue:       false,
		IsScholarly:      false,
	},
	{
		Slug:             "communal_ethos",
		IsDiplomatic:     false,
		IsWarlike:        false,
		IsAdministrative: true,
		IsIntrigue:       true,
		IsScholarly:      false,
	},
	{
		Slug:             "courtly_ethos",
		IsDiplomatic:     true,
		IsWarlike:        false,
		IsAdministrative: false,
		IsIntrigue:       false,
		IsScholarly:      true,
	},
	{
		Slug:             "egalitarian_ethos",
		IsDiplomatic:     true,
		IsWarlike:        false,
		IsAdministrative: true,
		IsIntrigue:       false,
		IsScholarly:      false,
	},
	{
		Slug:             "spiritual_ethos",
		IsDiplomatic:     false,
		IsWarlike:        false,
		IsAdministrative: true,
		IsIntrigue:       false,
		IsScholarly:      true,
	},
	{
		Slug:             "stoic_ethos",
		IsDiplomatic:     true,
		IsWarlike:        true,
		IsAdministrative: false,
		IsIntrigue:       false,
		IsScholarly:      false,
	},
}
