package culture

import "github.com/olehmushka/world-generator-engine/gender"

var mockTraditions = []*Tradition{
	{
		Slug:                "bound_by_faith_tradition",
		Description:         "In this culture being of a different faith means that you're not eligible for succession.",
		PreferredEthosSlugs: []string{"spiritual_ethos"},
		Type:                "ritual_tradition_type",
		OmitTraditionSlugs:  []string{},
		OmitGenderDominance: []gender.Sex{},
		OmitEthosSlugs:      []string{},
	},
	{
		Slug:                "frequent_festivities_tradition",
		Description:         "The frequency and exuberance with which this culture throws festivities would be considered vulgar to others, but a party is a party!",
		PreferredEthosSlugs: []string{"communal_ethos", "courtly_ethos", "stoic_ethos"},
		Type:                "ritual_tradition_type",
		OmitTraditionSlugs:  []string{},
		OmitGenderDominance: []gender.Sex{},
		OmitEthosSlugs:      []string{},
	},
	{
		Slug:                "linguists_tradition",
		Description:         "To learn the words of a neighbor brings you one step closer to the language of the Divine.",
		PreferredEthosSlugs: []string{"bureaucratic_ethos", "egalitarian_ethos", "spiritual_ethos"},
		Type:                "ritual_tradition_type",
		OmitTraditionSlugs:  []string{},
		OmitGenderDominance: []gender.Sex{},
		OmitEthosSlugs:      []string{},
	},
	{
		Slug:                "medicinal_herbalists_tradition",
		Description:         "This culture long ago developed knowledge of the medicinal properties of the plants and trees; to them most ailments are treatable with the right poultice, salve or stew.",
		PreferredEthosSlugs: []string{"bureaucratic_ethos", "stoic_ethos"},
		Type:                "ritual_tradition_type",
		OmitTraditionSlugs:  []string{},
		OmitGenderDominance: []gender.Sex{},
		OmitEthosSlugs:      []string{},
	},
	{
		Slug:                "by_the_sword_tradition",
		Description:         "Members of this culture believe that the best missionary is one carrying a sword. While support for holy wars are widespread, motives are scrutinized as to make sure the Divine powers would approve.",
		PreferredEthosSlugs: []string{"spiritual_ethos"},
		Type:                "ritual_tradition_type",
		OmitTraditionSlugs:  []string{},
		OmitGenderDominance: []gender.Sex{},
		OmitEthosSlugs:      []string{},
	},
	{
		Slug:                "concubines_tradition",
		Description:         "Rulers of this culture often keep a number of concubines in their household, regardless of their faith.",
		PreferredEthosSlugs: []string{"bellicose_ethos", "bureaucratic_ethos", "communal_ethos", "courtly_ethos", "egalitarian_ethos", "spiritual_ethos", "stoic_ethos"},
		Type:                "ritual_tradition_type",
		OmitTraditionSlugs:  []string{"monogamous_tradition", "polygamous_tradition"},
		OmitGenderDominance: []gender.Sex{},
		OmitEthosSlugs:      []string{},
	},
	{
		Slug:                "monogamous_tradition",
		Description:         "In this culture one keeps a single spouse, regardless of faith.",
		PreferredEthosSlugs: []string{"bellicose_ethos", "bureaucratic_ethos", "communal_ethos", "courtly_ethos", "egalitarian_ethos", "spiritual_ethos", "stoic_ethos"},
		Type:                "ritual_tradition_type",
		OmitTraditionSlugs:  []string{"concubines_tradition", "polygamous_tradition"},
		OmitGenderDominance: []gender.Sex{},
		OmitEthosSlugs:      []string{},
	},
	{
		Slug:                "polygamous_tradition",
		Description:         "In this culture one tend to have multiple spouses, regardless of faith.",
		PreferredEthosSlugs: []string{"bellicose_ethos", "bureaucratic_ethos", "communal_ethos", "courtly_ethos", "egalitarian_ethos", "spiritual_ethos", "stoic_ethos"},
		Type:                "ritual_tradition_type",
		OmitTraditionSlugs:  []string{"concubines_tradition", "monogamous_tradition"},
		OmitGenderDominance: []gender.Sex{},
		OmitEthosSlugs:      []string{},
	},
	{
		Slug:                "culinary_artists_tradition",
		Description:         "Food isn't just sustenance for this culture; it is both an art and a ritual, a focal point for family and community alike.",
		PreferredEthosSlugs: []string{"communal_ethos", "courtly_ethos", "spiritual_ethos"},
		Type:                "ritual_tradition_type",
		OmitTraditionSlugs:  []string{},
		OmitGenderDominance: []gender.Sex{},
		OmitEthosSlugs:      []string{},
	},
	{
		Slug:                "merciful_blindings_tradition",
		Description:         "No matter how far beyond forgiveness one has gone, this culture thinks it is better to gouge out an eye than run through a heart.",
		PreferredEthosSlugs: []string{"courtly_ethos", "spiritual_ethos"},
		Type:                "ritual_tradition_type",
		OmitTraditionSlugs:  []string{},
		OmitGenderDominance: []gender.Sex{},
		OmitEthosSlugs:      []string{},
	},
	{
		Slug:                "religion_blending_tradition",
		Description:         "Members of this culture often live together with those sharing different faiths and beliefs, and do well in adopting foreign elements into their own worship.",
		PreferredEthosSlugs: []string{"communal_ethos", "courtly_ethos", "spiritual_ethos"},
		Type:                "ritual_tradition_type",
		OmitTraditionSlugs:  []string{"steppe_tolerance_tradition"},
		OmitGenderDominance: []gender.Sex{},
		OmitEthosSlugs:      []string{},
	},
	{
		Slug:                "religious_patronage_tradition",
		Description:         "For the salvation of the soul, one must commit to works of religious significance. You cannot purchase redemption, but having a temple of priests sing your praises helps!",
		PreferredEthosSlugs: []string{"communal_ethos", "courtly_ethos", "spiritual_ethos"},
		Type:                "ritual_tradition_type",
		OmitTraditionSlugs:  []string{},
		OmitGenderDominance: []gender.Sex{},
		OmitEthosSlugs:      []string{},
	},
	{
		Slug:                "runestone_raisers_tradition",
		Description:         "Death, conquest, the acquisition of rank — are these not the things that define life in the nobility? Where our people go, so go the markers of our lives' worth.",
		PreferredEthosSlugs: []string{"bellicose_ethos", "bureaucratic_ethos"},
		Type:                "ritual_tradition_type",
		OmitTraditionSlugs:  []string{},
		OmitGenderDominance: []gender.Sex{},
		OmitEthosSlugs:      []string{},
	},
	{
		Slug:                "sacred_groves_tradition",
		Description:         "Trees are considered sacred by this culture. The forest is a living being that ought to be cared for—not destroyed.",
		PreferredEthosSlugs: []string{"spiritual_ethos"},
		Type:                "ritual_tradition_type",
		OmitTraditionSlugs:  []string{},
		OmitGenderDominance: []gender.Sex{},
		OmitEthosSlugs:      []string{},
	},
	{
		Slug:                "sacred_hunts_tradition",
		Description:         "Hunting is neither a sport nor a pastime, it is nothing less than the purest expression of the human experience, where one may connect with the divine by demonstrating their mastery over nature.",
		PreferredEthosSlugs: []string{"bellicose_ethos", "spiritual_ethos", "stoic_ethos"},
		Type:                "ritual_tradition_type",
		OmitTraditionSlugs:  []string{"vegetarians_tradition", "pacifists_tradition"},
		OmitGenderDominance: []gender.Sex{},
		OmitEthosSlugs:      []string{},
	},
	{
		Slug:                "sacred_mountains_tradition",
		Description:         "This culture considers mountains to be connections to the divine, and treats them with reverence and respect.",
		PreferredEthosSlugs: []string{"spiritual_ethos"},
		Type:                "ritual_tradition_type",
		OmitTraditionSlugs:  []string{},
		OmitGenderDominance: []gender.Sex{},
		OmitEthosSlugs:      []string{},
	},
	{
		Slug:                "sorcerous_metallurgy_tradition",
		Description:         "There are as many alchemists in this culture attempting to turn metal into gold as there are smiths forging weapons. What does it matter if this culture's wealth and weaponry are enhanced by witchcraft?",
		PreferredEthosSlugs: []string{"communal_ethos", "spiritual_ethos"},
		Type:                "ritual_tradition_type",
		OmitTraditionSlugs:  []string{},
		OmitGenderDominance: []gender.Sex{},
		OmitEthosSlugs:      []string{},
	},
	{
		Slug:                "tabletop_warriors_tradition",
		Description:         "Any commander can gamble and get lucky on the day of battle. A real strategist keeps their mind honed through practice and pretend, so that they have no need of 'luck'.",
		PreferredEthosSlugs: []string{"bellicose_ethos", "courtly_ethos"},
		Type:                "ritual_tradition_type",
		OmitTraditionSlugs:  []string{},
		OmitGenderDominance: []gender.Sex{},
		OmitEthosSlugs:      []string{},
	},
	{
		Slug:                "mystical_ancestors_tradition",
		Description:         "Lineage is very important to this culture, to the point where ancestors have become mythical and legendary beings with many who claim to be their descendants.",
		PreferredEthosSlugs: []string{"spiritual_ethos"},
		Type:                "ritual_tradition_type",
		OmitTraditionSlugs:  []string{},
		OmitGenderDominance: []gender.Sex{},
		OmitEthosSlugs:      []string{},
	},
}
